--WINDOW FUNCTIONS
--FIND THE TOTAL SALES ACROSS ALL ORDERS
SELECT 
SUM(Sales) TotalSales
FROM Sales.Orders

--FIND THE TOTAL SALES ACROSS EACH PRODUCT
SELECT 
	ProductId,
	SUM(SALES) TotalSales
FROM Sales.Orders
GROUP BY ProductId

--FIND THE TOTAL SALES ACROSS EACH PRODUCT AND ALSO ORDERID AND ORDERDATE
/*WRONG----
SELECT
OrderId,
OrderDate,
ProductId,
SUM(SALES) TotalSales
FROM Sales.Orders
GROUP BY ProductId,
OrderId,
OrderDate
*/

SELECT
ProductId,
OrderId,
OrderDate,
SUM(Sales) OVER(PARTITION BY ProductId) TotalSalesByProducts
FROM Sales.Orders

--FIND THE TOTAL SALES ACROSS ALL ORDERS ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE
SELECT
OrderId,
OrderDate,
SUM(Sales) OVER () TotalSales
FROM Sales.Orders

--FIND THE TOTAL SALES FOR EACH PRODUCT..ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE
SELECT 
OrderId,
OrderDate,
SUM(Sales) OVER (PARTITION BY ProductId) TotalSales
From Sales.Orders

--FIND THE TOTAL SALES ACROSS ALL ORDERS
--FIND THE TOTAL SALES FOR EACH PRODUCT..ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE
SELECT 
OrderId,OrderDate,
Sales,
SUM(Sales) OVER () TotalSales,
SUM(Sales) OVER (PARTITION BY ProductId)
FROM Sales.Orders;

--FIND THE TOTAL SALES FOR RACH COMBINATION OF PRODUCT AND ORDER STATUS
SELECT
OrderId,
OrderDate,
ProductId,
OrderStatus,
SUM(Sales) OVER () TotalSales,
SUM(Sales) OVER(PARTITION BY ProductId) TotalSalesByProducts,
SUM(Sales) OVER(PARTITION BY ProductId,OrderStatus) SalesByProductsAndStatus
FROM Sales.Orders

--RANK EACH 0ORDER BASED ON THEIR SALES FROM HIGHEST TO LOWEST.ADDITIONALLY PROVIDE ORDERID AND ORDERDATE
SELECT
OrderId,OrderDate,
sales,RANK()OVER (Order By Sales Desc) RankSales
FROM Sales.Orders

SELECT 
OrderId,OrderDate,
OrderStatus,
Sales,
SUM(Sales) OVER (PARTITION BY OrderStatus ORDER BY OrderDate
--ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) TotalSales
--ROWS BETWEEN 2 PRECEDING AND CURRENT ROW ) TotalSales,
--ROWS 2 PRECEDING) TotalSales
ROWS UNBOUNDED PRECEDING) TotalSales
--NOT ALLOWED
--ROWS 2 FOLLOWING) TotalSales
--ROWS UNBOUNDED FOLLOWING) TotalSales
FROM Sales.Orders

SELECT
OrderID,OrderDate,
Sales,SUM(Sales) OVER(PARTITION  BY OrderStatus) TotalSales
FROM Sales.Orders
ORDER BY SUM(Sales) OVER(PARTITION BY OrderStatus) DESC
--NOT ALLOWED
--WHERE SUM(Sales) OVER(PARTITION BY OrderStatus)>100
--GROUP BY SUM(Sales) OVER(PARTITION BY OrderStatus)
--SUM(SUM(Sales) OVER(PARTITION BY OrderStatus) DESC) OVER(PARTITION  BY OrderStatus) TotalSales

--FIND THE TOTAL SALES FOR EACH ORDER STATUS,ONLY FOR PRODUCTS 101 AND 102
SELECT
OrderID,OrderDate,
OrderStatus,ProductID,
Sales,
SUM(Sales)OVER(PARTITION BY OrderStatus)TotalSales
FROM Sales.orders
WHERE ProductID IN(101,102)

--RANK CUSTOMERS ON THEIR TOTAL SALES
SELECT
CustomerID,
SUM(Sales)TotalSales,
RANK() OVER( ORDER BY SUM(Sales) DESC) RankCustomers
FROM Sales.Orders
GROUP BY CustomerID

