--JOINS
/*
--NO JOIN
--Retrieve all data from customers and orders as separate result
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

--INNER JOIN
--GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER
SELECT *
FROM customers 
INNER JOIN orders
--ON customers.id=orders.customer_id;
ON id=customer_id;

--GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER
SELECT customers.id,first_name,orders.order_id,sales
FROM customers 
INNER JOIN orders
--ON customers.id=orders.customer_id;
ON id=customer_id;

--LEFT JOIN
--GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS INCLUDING THOSE WITHOUT ORDERS
SELECT *
FROM CUSTOMERS AS c
LEFT JOIN ORDERS AS o
ON c.id=o.customer_id

--RIGHT JOIN
--GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS INCLUDING ORDERS WITHOUT MATCHING CUSTOMERS
SELECT * 
FROM CUSTOMERS AS c
RIGHT JOIN ORDERS as o
ON c.id=o.customer_id

--SOLVE BY LEFT JOIN
SELECT * 
FROM ORDERS AS O
LEFT JOIN CUSTOMERS AS C
ON C.ID=O.CUSTOMER_ID;

--GET ALL THE CUSTOMERS AND ORDERS EVEN IF THERE IS NO MATCH
SELECT	
	c.id,
	c.first_name,
	o.order_id,
	o.sales
FROM customers AS c
FULL JOIN orders AS o
ON c.id=o.customer_id

--LEFT ANTI JOIN
--GET ALL THE CUSTOMERS WHO HAVE NOT PLACED ANY ORDERS
SELECT *
FROM CUSTOMERS AS c
LEFT JOIN orders AS o
ON c.id=o.customer_id
WHERE o.customer_id IS NULL 

--RIGHT ANTI JOIN
--GET ALL THE ORDERS WITHOUT MATCHING CUSTOMERS
SELECT *
FROM customers AS C
RIGHT JOIN orders AS O
ON c.id=o.customer_id
WHERE c.id IS NULL

Select *
from orders AS o
LEFT JOIN customers AS c
ON c.id=o.customer_id
WHERE C.ID IS NULL


--FULL ANTI JOIN
--GET ALL THE CUSTOMERS WITHOUT ORDERS AND ORDERS WITHOUT CUSTOMERS
SELECT *
FROM orders AS o
FULL JOIN customers AS c
ON c.id=o.customer_id
WHERE c.id IS NULL
OR
o.customer_id IS NULL;

--GET ALL THE CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY FOR CUSTOMERS WHO HAVE PLACED AN ORDER(WITHOUT USING INNER JOIN)
SELECT *
FROM CUSTOMERS AS C
FULL JOIN  ORDERS AS O
ON C.ID=O.CUSTOMER_ID
WHERE(NOT(C.ID IS NULL OR O.CUSTOMER_ID IS NULL));

SELECT *
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON O.CUSTOMER_ID=C.ID
WHERE (NOT(O.CUSTOMER_ID IS NULL));

SELECT *
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON O.CUSTOMER_ID=C.ID
WHERE O.CUSTOMER_ID IS NOT NULL;

--CROSS JOIN
--GENERATE ALL POSSIBLE COMBINATIONS OF ORDERS AND CUSTOMERS
SELECT *
FROM customers
CROSS JOIN orders


--MULTI TABLE JOIN
--USING SALESDB RETRIEVE A LIST OF ALL ORDERS ALONG WITH THE RELATED CUTOMERS,PRODUCT AND EMPLOYEE DETAILS
--ORDERS IS THE MAIN TABLE
USE SALESDB
SELECT 
o.OrderID,
o.Sales,
c.FirstName AS CustomerFirstName,
c.LastName AS CustomerLastName,
p.Product AS PRODUCT_NAME,
p.Price,
e.FirstName AS EmployeeFirstName,
e.LastName AS EmployeeLastName
FROM SALES.ORDERS AS o
LEFT JOIN Sales.Customers AS c
On o.CustomerID=c.CustomerId
LEFT JOIN Sales.Products AS p
ON o.ProductId=p.ProductId
LEFT JOIN Sales.Employees AS e
ON o.SalesPersonId=e.EmployeeId

*/
