--WINDOW AGGREGATE FUNCTIONS
/*
--COUNT
--FIND THE TOTAL NUMBER OF ORDERS FOR EACH PRODUCT
--FIND THE TOTAL NUMBER OF SALES FOR EACH PRODUCT

--FIND THE TOTAL NUMBER OF ORDERS
SELECT
COUNT(*) 
FROM Sales.Orders

--FIND THE TOTAL NUMBER OF ORDERS.ADDITIONALLY PROVIDE DETAILS LIKE ORDERID,ORDERDATE
SELECT
OrderID,
OrderDate,
COUNT(*) OVER() TotalOrders
FROM Sales.Orders

--FIND THE TOTAL NUMBER OF ORDERS FOR EACH CUSTOMERS
SELECT
OrderID,
OrderDate,
CustomerId,
COUNT(*) OVER() TotalOrders,
COUNT(*) OVER(PARTITION BY CustomerID) OrdersByCustomers
FROM Sales.Orders

--FIND THE TOTAL NUMBERS OF CUSTOMERS.ADDITIONALLY PROVIDE ALL CUSTOMERS DETAILS
SELECT
	*,
	COUNT(*) OVER () TotalCustomerStar,
	COUNT(1) OVER() TotalCustomersOne
FROM Sales.Customers

--FIND THE TOTAL NUMBER OF SCORES FOR THE CUSTOMERS
SELECT
COUNT(Score) OVER() TotalScores,
COUNT(Country) OVER() TotalCountries
FROM Sales.Customers

--CHECK WHETHER THE ORDER CONTAINS ANY DUPLICATE ROWS
SELECT
OrderID,
COUNT(*) OVER(PARTITION BY OrderID) CheckPK
FROM SALES.ORDERS

SELECT
*,
COUNT(*) OVER(PARTITION BY OrderID) CheckPk
FROM Sales.OrdersArchive

SELECT 
*
FROM(
SELECT
OrderID,
COUNT(*) OVER(PARTITION BY OrderID) CheckPK
FROM Sales.OrdersArchive
)t
WHERE CheckPK>1

--SUM
--FIND THE TOTAL SALES ACROSS ALL ORDERS AND THE TOTAL SALES FOR EACH PRODUCT
--ADDITIONALLY PROVIDE DETAILS LIKE ORDERID,ORDERDATE
SELECT
OrderID,
OrderDate,
Sales,
SUM(Sales) OVER () TotalSales,
SUM(Sales) OVER(PARTITION BY ProductID) SalesByProducts
FROM Sales.Orders

--FIND THE PERCENTAGE CONTRIBUTION OF EACH PRODUCTS SALES TO THE TOTAL SALES
SELECT
OrderID,
ProductID,
Sales,
SUM(Sales) OVER () TotalSales,
ROUND(CAST(Sales AS Float)/SUM(Sales) OVER ()*100,2)PERCENTAGEOFTOTAL
--SALES IS INT SO CANT GET FLOAT
FROM Sales.Orders
--PART TO WHOLE ANALYSIS :SHOWS THE CONTRIBUTION OF EACH DATA POINT TO OVERALL DATASET

--AVG
--FIND THE AVERAGE SALES ACROSS ALL ORDERS AND AVERAGE SALES FOR EACH PRODUCT.
--Additionally give OrderID AND ORDERDATE
SELECT
	OrderID,
	OrderDate,
	AVG(Sales) OVER () AVGSALES,
	AVG(Sales) OVER (PARTITION BY ProductID) AVGSALESBYPRODUCTS
FROM Sales.Orders

--FIND THE AVERAGE SCORES OF CUSTOMERS.ADDITIONALLY PROVIDE DETAILS LIKE CUSTOMERID AND LASTNAME
SELECT
CustomerID,
LastName,
Score,
COALESCE(Score,0) CustomerScore,
AVG(Score) OVER() AvgScore,
AVG(COALESCE(Score,0))OVER() AvgScoreWithoutNull
FROM Sales.Customers

--FIND ALL ORDERS WHERE SALES ARE HIGHER THAN THE AVERAGE SALES ACROSS ALL ORDERS
SELECT
*
FROM(
SELECT
OrderID,
ProductID,
Sales,
AVG(Sales)OVER () AvgSales
FROM Sales.Orders)t
WHERE Sales>AvgSales
*/

--MIN/MAX
--FIND THE highest and lowest SALES ACROSS ALL ORDERS AND highest and lowest  SALES FOR EACH PRODUCT.
--Additionally give OrderID AND ORDERDATE
SELECT
	OrderID,
	OrderDate,
	ProductID,
	Sales,
	MAX(Sales) OVER() HighestSales,
	MIN(Sales) OVER() LowestSales,
	MAX(Sales) OVER(PARTITION BY ProductID) HighestSalesByProduct,
	MIN(Sales) OVER(PARTITION BY ProductID) LowestSalesByProduct
FROM Sales.Orders

--SHOW THE EMPLOYEES WITH THE HIGHEST SALARIES
SELECT *
FROM(
SELECT
*,
MAX(Salary) OVER () HighestSalary
FROM Sales.Employees)t
Where Salary=HighestSalary

--CALCULATE THE DEVIATION OF EACH SALE FROM BOTH THE MINIMUM AND MAXIMUM SALE AMOUNTS
SELECT *
FROM(
SELECT 
	OrderID,
	OrderDate,
	ProductID,
	Sales,
	MAX(Sales) OVER () HighestSales,
	MIN(Sales) OVER () LowestSales,
	Sales-MIN(Sales) OVER() DEVIATION_FROM_MIN,
	Max(Sales) Over()-Sales DEVIATION_FROM_MAX
	FROM Sales.Orders
)t

--CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME
SELECT
	OrderID,
	OrderDate,
	ProductID,
	Sales,
	AVG(Sales) OVER(PARTITION BY ProductID) AvgByProduct,
	AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate) MOVINGAVG

FROM Sales.Orders

--CALCULATE THE MOVING AVERAGE OF SALES FOR EACH PRODUCT OVER TIME including only the next order
SELECT
	OrderID,
	OrderDate,
	ProductID,
	Sales,
	AVG(Sales) OVER(PARTITION BY ProductID) AvgByProduct,
	AVG(Sales) OVER(PARTITION BY ProductID ORDER BY OrderDate) MOVINGAVG,
	AVG(Sales) OVER(PARTITION BY ProductID Order BY OrderDate ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) RollingAvg
FROM Sales.Orders

